library(distributedR)
library(Matrix)
data_path<-system.file("extdata",package="distributedR")

context("checking invalid creation of dlist")

test_that("Dlist: invalid creation of dlist", {
 
  expect_error(dlist("1"))
  expect_error(dlist(100/3))
  expect_error(dlist(c(1,1), c(2,2)))
  expect_error(dlist(c(-10,10),c(1,5)))
  expect_error(dlist(c("a",1), c(4,"c")))
  expect_error(dlist(c(1,2,3),c(4,2)))
  expect_error(dlist(c(10,10),c(0,10)))
  expect_error(dlist(wrongarg=c(2,4)))
  expect_error(dlist(c(4,4), c(2,4), sparse=TRUE))
  expect_error(dlist(c(4,4), c(2,4)))
  
  mdl <- list()
  dl1 <- dlist(npartitions=5)
  dl1gp <- getpartition(dl1)
  dl1gp2 <- getpartition(dl1, 2)
  expect_error(getpartition(dl1, 6))
  expect_true(class(dl1gp)=="list")
  expect_true(is.dlist(dl1))
  expect_equal(1, splits(dl1)@split_ids[2])
  expect_equal(0, splits(dl1,1)@split_ids[1])
  expect_error(getpartition(dl1, 0))
  expect_error(getpartition(dl1, 6))
  expect_error(getpartition(dl1, -100))
  expect_error(getpartition(dl1, mdl))
  expect_error(splits(dl1,0))
  expect_error(splits(dl1,6))
})

context("testing row/column name and value setup")

test_that("Dlist: testing row/column name and value setup",{
  dl2 <- dlist(npartitions=10)
  empty_list <- list()
  expect_equal(10, length(splits(dl2)@split_ids))  
  dl2gp <- getpartition(dl2)
  dl2gp5 <- getpartition(dl2, 5)
  dl2gp10 <- getpartition(dl2, 10)
  expect_true(all(dl2gp== empty_list))
  expect_true(all(dl2gp5== empty_list))
  expect_true(all(dl2gp10== empty_list))

  A <- list(2, c("fred", "mary"), 3, list(10, 20, 30), matrix(2,4,5))
  A1 <- list(2)
  A2 <- list(c("fred", "mary"), 3)
  A3 <- list(list(10, 20, 30), matrix(2,4,5))
  dl3 <- dlist(3)
  foreach(i, 1, init <- function(a=splits(dl3, i)) {a <- list(2); update(a);})
  foreach(i, 2, init <- function(a=splits(dl3, i)) {a <- list(c("fred", "mary"), 3); update(a);})
  foreach(i, 3, init <- function(a=splits(dl3, i)) {a <- list(list(10, 20, 30), matrix(2,4,5)); update(a);}) 
  dl3gp <- getpartition(dl3)
  dl3gp1 <- getpartition(dl3, 1)
  dl3gp2 <- getpartition(dl3, 2)
  dl3gp3 <- getpartition(dl3, 3)
  expect_equal(A, dl3gp)
  expect_equal(A1, dl3gp1)
  expect_equal(A2, dl3gp2)
  expect_equal(A3, dl3gp3)  

  A <- append(A, list(list(100,128.987,-1.234), c(TRUE, FALSE, TRUE)))
  A1 <- list(2, c("fred", "mary"), 3)
  A2 <- list(list(10, 20, 30), matrix(2,4,5), list(100,128.987,-1.234))
  A3 <- list(c(TRUE, FALSE, TRUE))
  foreach(i, 1, init <- function(a=splits(dl3)) {a <- append(a, list(list(100,128.987,-1.234), c(TRUE, FALSE, TRUE))); update(a);})
  dl3gp <- getpartition(dl3)
  dl3gp1 <- getpartition(dl3, 1)
  dl3gp2 <- getpartition(dl3, 2)
  dl3gp3 <- getpartition(dl3, 3) 
  expect_equal(A, dl3gp)
  expect_equal(A1, dl3gp1)
  expect_equal(A2, dl3gp2)
  expect_equal(A3, dl3gp3)
})
