// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// EnableMMapHooks
void EnableMMapHooks();
RcppExport SEXP ooclibrary_EnableMMapHooks() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    EnableMMapHooks();
    return R_NilValue;
END_RCPP
}
// PrintMMapStatus
void PrintMMapStatus();
RcppExport SEXP ooclibrary_PrintMMapStatus() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    PrintMMapStatus();
    return R_NilValue;
END_RCPP
}
// SetMemoryLimit
void SetMemoryLimit(int mega);
RcppExport SEXP ooclibrary_SetMemoryLimit(SEXP megaSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type mega(megaSEXP);
    SetMemoryLimit(mega);
    return R_NilValue;
END_RCPP
}
// LockAll
void LockAll();
RcppExport SEXP ooclibrary_LockAll() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    LockAll();
    return R_NilValue;
END_RCPP
}
// LockAllPeriodically
void LockAllPeriodically(size_t t);
RcppExport SEXP ooclibrary_LockAllPeriodically(SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< size_t >::type t(tSEXP);
    LockAllPeriodically(t);
    return R_NilValue;
END_RCPP
}
