CLASSPATH=-cp ./rsession-read-only/Rsession/dist/lib/Rsession-1.8.jar:./rsession-read-only/Rsession/dist/lib/REngine-1.8.jar:./rsession-read-only/Rsession/dist/lib/RserveEngine-1.8.jar:.

all:
	javac $(CLASSPATH) Example1.java
	java $(CLASSPATH) Example1
