# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeFactors <- function(ls, fs, rs, lambda, numFactors) {
	.Call('HPdrecommend_computeFactors', PACKAGE = 'HPdrecommend', ls, fs, rs, lambda, numFactors)
}

countNonzeros <- function(R) {
	.Call('HPdrecommend_countNonzeros', PACKAGE = 'HPdrecommend', R)
}

gatherPartitionInfo <- function(U, Rrow, numPartitions) {
	partInfo <- dlist(npartitions(U))
	foreach(k, 1:npartitions(U),
		function(us = splits(U, k),
				rs = splits(Rrow, k),
				dl = splits(partInfo, k),
				np = numPartitions) {
			library(HPdrecommend)
			p <- .Call('HPdrecommend_gatherPartitionInfo', PACKAGE = 'HPdrecommend', us, rs, np)
			p <- which(p == 1)
			dl <- list((p))
			update(dl)
		}
	)
	return(partInfo)
}
