# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EnableMMapHooks <- function() {
    invisible(.Call('ooclibrary_EnableMMapHooks', PACKAGE = 'ooclibrary'))
}

PrintMMapStatus <- function() {
    invisible(.Call('ooclibrary_PrintMMapStatus', PACKAGE = 'ooclibrary'))
}

SetMemoryLimit <- function(mega) {
    invisible(.Call('ooclibrary_SetMemoryLimit', PACKAGE = 'ooclibrary', mega))
}

LockAll <- function() {
    invisible(.Call('ooclibrary_LockAll', PACKAGE = 'ooclibrary'))
}

LockAllPeriodically <- function(t) {
    invisible(.Call('ooclibrary_LockAllPeriodically', PACKAGE = 'ooclibrary', t))
}

