#!/bin/bash

#####################################################################
#Copyright (C) [2014] Hewlett-Packard Development Company, L.P.

#This program is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or (at
#your option) any later version.

#This program is distributed in the hope that it will be useful, but
#WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#General Public License for more details.  You should have received a
#copy of the GNU General Public License along with this program; if
#not, write to the Free Software Foundation, Inc., 59 Temple Place,
#Suite 330, Boston, MA 02111-1307 USA
#####################################################################

rm -rf  /tmp/distributedR_addons/
mkdir -pv /tmp/distributedR_addons
chmod 777 /dev/shm

/sbin/ldconfig -v > /tmp/distributedR_addons/ldconfig.log 2>&1
for ADDON in Rcpp_0.10.6.tar.gz RInside_0.2.10.tar.gz XML_3.98-1.1.tar.gz data.table_1.8.10.tar.gz randomForest_4.6-7.tar.gz; do
    echo "Installing $ADDON"
    echo "Installing $ADDON" >>  /tmp/distributedR_addons/vertica_distributedR_addon_install.log
    R CMD INSTALL /opt/hp/distributedR/third_party/R_addons/$ADDON >> /tmp/distributedR_addons/vertica_distributedR_addon_install.log 2>&1
    if [ $? -ne 0 ]; then
        echo "... error"
        exit 1
    fi
    /sbin/ldconfig -v >> /tmp/distributedR_addons/ldconfig.log 2>&1
done

for thing in distributedR Executor MatrixHelper; do
    echo "Installing $thing"
    echo "Installing $thing" >>  /tmp/distributedR_addons/vertica_distributedR_addon_install.log
    R CMD INSTALL --no-html /opt/hp/distributedR/install/$thing >> /tmp/distributedR_addons/vertica_distributedR_addon_install.log 2>&1
    if [ $? -ne 0 ]; then
        echo "... error"
        exit 1
    fi
    /sbin/ldconfig -v >> /tmp/distributedR_addons/ldconfig.log 2>&1
done

for ADDON in HPDGLM HPdcluster HPdgraph HPdclassifier HPdata; do
    echo "Installing $ADDON"
    echo "Installing $ADDON" >>  /tmp/distributedR_addons/vertica_distributedR_addon_install.log
    R CMD INSTALL /opt/hp/distributedR/third_party/R_addons/$ADDON >> /tmp/distributedR_addons/vertica_distributedR_addon_install.log 2>&1
    if [ $? -ne 0 ]; then
        echo "... error"
        exit 1
    fi
    /sbin/ldconfig -v >> /tmp/distributedR_addons/ldconfig.log 2>&1
done
